// ==================== CONSTANTS AND CONFIGURATION ====================

export const LOGODEV_API_KEY = "pk_Mugixd0DTQO4N80QR6b0_g";

export const osmTags = {
  school: "amenity=school|amenity=university|amenity=college",
  hospital: "amenity=hospital|amenity=clinic|healthcare=hospital",
  fast_food: "amenity=fast_food|amenity=restaurant",
  supermarket: "shop=supermarket|shop=grocery|shop=convenience",
  shopping_mall: "shop=mall|shop=department_store",
  coffee_shop: "amenity=cafe|shop=coffee",
  gas_station: "amenity=fuel|shop=gas",
  police_station: "amenity=police",
  fire_station: "amenity=fire_station",
  bank: "amenity=bank",
  park: "leisure=park|leisure=garden",
  pharmacy: "amenity=pharmacy|shop=pharmacy|shop=chemist",
  gym: "leisure=fitness_centre|leisure=sports_centre|leisure=gym|amenity=gym",
  other: "amenity=*|shop=*|leisure=*", // ✅ ADD THIS LINE FOR SEARCH RESULTS
};

export const categoryIcons = {
  school: "🏫",
  hospital: "🏥",
  fast_food: "🍔",
  supermarket: "🛒",
  shopping_mall: "🏬",
  coffee_shop: "☕",
  gas_station: "⛽",
  police_station: "👮",
  fire_station: "🚒",
  bank: "🏦",
  park: "🌳",
  pharmacy: "💊",
  gym: "💪",
};

export const FAMOUS_LOCATIONS = [
  "Statue of Liberty",
  "Grand Canyon",
  "Times Square",
  "Golden Gate Bridge",
  "Empire State Building",
  "White House",
  "Disney World",
  "Disneyland",
  "Universal Studios",
  "Space Needle",
  "Central Park",
  "Navy Pier",
  "Pike Place Market",
  "Fenway Park",
  "Mall of America",
  "King of Prussia Mall",
  "South Coast Plaza",
  "Aventura Mall",
  "The Grove",
  "Tysons Corner Center",
  "Harvard University",
  "Stanford University",
  "MIT",
  "Yale University",
  "Princeton University",
  "Mayo Clinic",
  "Cleveland Clinic",
  "Johns Hopkins Hospital",
];
// ✅ NEW: Famous BRANDS list (for all other categories except popularLocations)

export const FAMOUS_BRANDS = [
  "Walmart",
  "Target",
  "Costco",
  "Sam’s Club",
  "BJ’s Wholesale Club",
  "Amazon",
  "The Home Depot",
  "Lowe’s",
  "Menards",
  "IKEA",
  "Best Buy",
  "Macy’s",
  "Nordstrom",
  "Kohl’s",
  "KFC",
  "Marco's Pizza",
  "Pizza Hut",
  "Domino’s Pizza",
  "Pizza Hut Express",
  "Papa John’s",
  "Domino’s",
  "Dominos",
  "Subway",
  "Burger King",
  "Wendy’s",
  "Taco Bell",
  "Chick-fil-A",
  "Arby’s",
  "Sonic Drive-In",
  "Dunkin’",
  "Starbucks",
  "Chipotle Mexican Grill",
  "Panera Bread",
  "Olive Garden",
  "JCPenney",
  "Dillard’s",
  "Bloomingdale’s",
  "Neiman Marcus",
  "Saks Fifth Avenue",
  "TJ Maxx",
  "Marshalls",
  "HomeGoods",
  "Ross Dress for Less",
  "Burlington",
  "Bed Bath & Beyond",
  "Williams-Sonoma",
  "Pottery Barn",
  "West Elm",
  "Crate & Barrel",
  "Restoration Hardware",
  "Wayfair",
  "Overstock",
  "At Home",
  "Michael’s",
  "Hobby Lobby",
  "Jo-Ann Fabrics & Crafts",
  "Party City",
  "Barnes & Noble",
  "Books-A-Million",
  "GameStop",
  "Foot Locker",
  "DSW",
  "Finish Line",
  "Shoe Carnival",
  "Famous Footwear",
  "Nordstrom Rack",
  "Saks OFF 5TH",
  "NikE",
  "Adidas",
  "Under Armour",
  "Puma",
  "New Balance",
  "Vans",
  "Converse",
  "Skechers",
  "Gap",
  "Old Navy",
  "Banana Republic",
  "J.Crew",
  "Madewell",
  "Express",
  "Ann Taylor",
  "Loft",
  "Talbots",
  "Brooks Brothers",
  "Jos. A. Bank",
  "Men’s Wearhouse",
  "Abercrombie & Fitch",
  "Hollister",
  "American Eagle Outfitters",
  "Aerie",
  "H&M (US)",
  "Zara (US)",
  "Uniqlo (US)",
  "Forever 21",
  "Urban Outfitters",
  "Anthropologie",
  "Free People",
  "Lululemon",
  "Athleta",
  "Victoria’s Secret",
  "Bath & Body Works",
  "Sephora",
  "Ulta Beauty",
  "Claire’s",
  "Build-A-Bear Workshop",
  "Carter’s",
  "OshKosh B’gosh",
  "The Children’s Place",
  "Gymboree",
  'Toys"R"Us',
  "Five Below",
  "Dollar General",
  "Dollar Tree",
  "Family Dollar",
  "Big Lots",
  "Staples",
  "Office Depot",
  "OfficeMax",
  "The Container Store",
  "Kroger",
  "Safeway",
  "Albertsons",
  "Publix",
  "Wegmans",
  "H-E-B",
  "Meijer",
  "Giant Eagle",
  "Stop & Shop",
  "Food Lion",
  "Trader Joe’s",
  "Whole Foods Market",
  "Aldi",
  "WinCo Foods",
  "Sprouts Farmers Market",
  "Hy-Vee",
  "Fred Meyer",
  "Ralphs",
  "King Soopers",
  "Piggly Wiggly",
  "Harris Teeter",
  "Food 4 Less",
  "Giant Food (Mid-Atlantic)",
  "Shaw’s",
  "Hannaford",
  "Price Chopper / Market 32",
  "Big Y",
  "Stater Bros. Markets",
  "Save-A-Lot",
  "Ingles Markets",
  "The Fresh Market",
  "Bashas’",
  "Smart & Final",
  "Grocery Outlet",
  "Central Market",
  "Market Basket",
  "Fairway Market",
  "Save Mart",
  "Vons",
  "King Kullen",
  "Marriott International",
  "Hilton Worldwide",
  "Hyatt",
  "InterContinental Hotels Group",
  "Wyndham Hotels & Resorts",
  "Choice Hotels International",
  "Radisson Hotel Group",
  "Four Seasons Hotels & Resorts",
  "Ritz-Carlton",
  "Omni Hotels & Resorts",
  "Loews Hotels",
  "Drury Hotels",
  "Kimpton Hotels",
  "Aloft Hotels",
  "W Hotels",
  "JW Marriott",
  "Sheraton Hotels & Resorts",
  "Westin Hotels & Resorts",
  "Courtyard by Marriott",
  "Residence Inn by Marriott",
  "SpringHill Suites",
  "TownePlace Suites",
  "Homewood Suites by Hilton",
  "Home2 Suites by Hilton",
  "Hampton Inn",
  "DoubleTree",
  "Best Western Hotels & Resorts",
  "Comfort Inn",
  "Days Inn",
  "Motel 6",
  "Red Roof Inn",
  "Extended Stay America",
  "La Quinta by Wyndham",
  "Fairfield Inn & Suites",
  "Embassy Suites by Hilton",
  "Shell",
  "Chevron",
  "ExxonMobil",
  "BP",
  "Marathon Petroleum",
  "Phillips 66",
  "Valero",
  "Sunoco",
  "Conoco (ConocoPhillips)",
  "7-Eleven",
  "Circle K",
  "Wawa",
  "Sheetz",
  "QuikTrip",
  "Love’s Travel Stops & Country Stores",
  "Pilot Flying J",
  "Casey’s General Store",
  "Cumberland Farms",
  "RaceTrac",
  "Kwik Trip / Kwik Star",
  "ARCO",
  "Texaco",
  "Hess",
  "MAPCO Express",
  "Murphy USA",
  "Stewart’s Shops",
  "CVS Pharmacy",
  "Walgreens",
  "Rite Aid",
  "Duane Reade",
  "Walmart Pharmacy",
  "Kroger Pharmacy",
  "Target Pharmacy",
  "Costco Pharmacy",
  "Publix Pharmacy",
  "Albertsons Pharmacy",
  "Sam’s Club Pharmacy",
  "H-E-B Pharmacy",
  "Safeway Pharmacy",
  "Longs Drugs",
  "Health Mart",
  "OptumRx",
  "Walgreens Boots Alliance",
  "Good Neighbor Pharmacy",
  "Medicine Shoppe",
  "Fred’s Pharmacy",
  "Bank of America",
  "JPMorgan Chase",
  "Wells Fargo",
  "Citibank",
  "U.S. Bank",
  "PNC Bank",
  "Capital One",
  "TD Bank",
  "Regions Bank",
  "Fifth Third Bank",
  "Huntington Bank",
  "KeyBank",
  "M&T Bank",
  "Truist Financial",
  "BMO Harris Bank",
  "Comerica Bank",
  "First Republic Bank",
  "Ally Bank",
  "Charles Schwab",
  "Morgan Stanley",
  "Raymond James",
  "American Express",
  "Discover Financial Services",
  "Fidelity Investments",
  "UPS",
  "FedEx",
  "USPS",
  "DHL",
  "The UPS Store",
  "FedEx Office",
  "Amazon Hub",
  "Western Union",
  "MoneyGram",
  "H&R Block",
  "Jackson Hewitt",
  "Liberty Tax Service",
  "ADP",
  "TurboTax",
  "AutoZone",
  "Advance Auto Parts",
  "O’Reilly Auto Parts",
  "NAPA Auto Parts",
  "Pep Boys",
  "Carquest Auto Parts",
  "Jiffy Lube",
  "Valvoline Instant Oil Change",
  "Midas",
  "Meineke",
  "Firestone Complete Auto Care",
  "Goodyear Auto Service",
  "NTB",
  "Take 5 Oil Change",
  "Express Oil Change & Tire Engineers",
  "Tire Kingdom",
  "Discount Tire",
  "Les Schwab Tire Centers",
  "CarMax",
  "Carvana",
  "Vroom",
  "Enterprise Rent-A-Car",
  "National Car Rental",
  "Alamo Rent A Car",
  "Hertz",
  "Avis",
  "Budget Rent A Car",
  "Dollar Rent A Car",
  "Thrifty Car Rental",
  "Sixt Rent A Car",
  "U-Haul",
  "Penske Truck Rental",
  "Ryder",
  "PODS",
  "Two Men and a Truck",
  "Mayflower Transit",
  "Allied Van Lines",
  "Bekins Van Lines",
  "Public Storage",
  "Extra Space Storage",
  "CubeSmart",
  "Life Storage",
  "StorageMart",
  "1-800-PACK-RAT",
  "Zippy Shell",
  "Mobile Mini",
  "AMC Theatres",
  "Regal Cinemas",
  "Cinemark Theatres",
  "Marcus Theatres",
  "Alamo Drafthouse Cinema",
  "Landmark Theatres",
  "Bow Tie Cinemas",
  "iPic Theaters",
  "Harkins Theatres",
  "B&B Theatres",
  "Dave & Buster's",
  "Main Event Entertainment",
  "Topgolf",
  "Round1",
  "Bowlero",
  "Lucky Strike Lanes",
  "Chuck E. Cheese",
  "Medieval Times",
  "SEA LIFE",
  "Six Flags Entertainment Corporation",
  "Cedar Fair",
  "Universal Parks & Resorts",
  "Walt Disney Parks & Resorts",
  "SeaWorld Parks & Entertainment",
  "Busch Gardens",
  "LEGOLAND",
  "Dollywood",
  "Knott's Berry Farm",
  "Silver Dollar City",
  "Planet Fitness",
  "LA Fitness",
  "24 Hour Fitness",
  "Gold's Gym",
  "Anytime Fitness",
  "Crunch Fitness",
  "Orangetheory Fitness",
  "Equinox",
  "Lifetime Fitness",
  "YMCA",
  "Massage Envy",
  "European Wax Center",
  "Supercuts",
  "Great Clips",
  "Sport Clips",
  "Regis Salons",
  "Fantastic Sams",
  "Hand & Stone Massage and Facial Spa",
  "Drybar",
  "PetSmart",
  "Petco",
  "Banfield Pet Hospital",
  "VCA Animal Hospitals",
  "Pet Supplies Plus",
  "Pet Supermarket",
  "Wag N’ Wash",
  "PetPeople",
  "Apple Store",
  "Microsoft Store",
  "Best Buy Mobile",
  "Verizon Wireless",
  "AT&T",
  "T-Mobile",
  "Sprint",
  "Cricket Wireless",
  "Boost Mobile",
  "Metro by T-Mobile",
  "DoorDash",
  "Grubhub",
  "Uber Eats",
  "Postmates",
  "Instacart",
  "Blue Apron",
  "HelloFresh",
  "Sun Basket",
  "Freshly",
  "Goldbelly",
  "Seamless",
  "Caviar",
  "Delivery.com",
  "Slice",
  "Waitr",
  "Favor",
  "Shipt",
  "GoPuff",
  "Drizly",
  "Saucey",
  "Yelp",
  "Groupon",
  "LivingSocial",
  "OpenTable",
  "Resy",
  "Toast",
  "Square",
  "Clover",
  "Revel Systems",
  "Lightspeed",
  "Terminix",
  "Orkin",
  "ServiceMaster",
  "Stanley Steemer",
  "Servpro",
  "Roto-Rooter",
  "Mr. Rooter",
  "Benjamin Franklin Plumbing",
  "TruGreen",
  "Scotts LawnService",
  "The Grounds Guys",
  "U.S. Lawns",
  "Mosquito Joe",
  "Handy",
  "Angi",
  "Thumbtack",
  "HomeAdvisor",
  "Redbox",
  "Netflix",
  "Hulu",
  "Amazon Prime Video",
  "Spotify",
  "Pandora",
  "iHeartRadio",
  "SiriusXM",
  "Ticketmaster",
  "Live Nation",
  "Panera Bread",
  "Shake Shack",
  "Whataburger",
  "Raising Cane's",
  "Culver's",
  "Jimmy John's",
  "Jersey Mike's",
  "Firehouse Subs",
  "Papa John's",
  "MOD Pizza",
  "Blaze Pizza",
  "Qdoba",
  "Moe's Southwest Grill",
  "Del Taco",
  "White Castle",
  "Krystal",
  "Bojangles",
  "El Pollo Loco",
  "Church's Chicken",
  "Wingstop",
  "Buffalo Wild Wings",
  "Zaxby's",
  "Hooters",
  "Olive Garden",
  "Applebee's",
  "Chili's",
  "IHOP",
  "Denny's",
  "Red Lobster",
  "Outback Steakhouse",
  "Cracker Barrel",
  "Texas Roadhouse",
  "Cheesecake Factory",
  "TGI Fridays",
  "LongHorn Steakhouse",
  "P.F. Chang's",
  "Ruby Tuesday",
  "Golden Corral",
  "Bob Evans",
  "Perkins",
  "Waffle House",
  "Dairy Queen",
  "Baskin-Robbins",
  "Krispy Kreme",
  "Cold Stone Creamery",
  "Cinnabon",
  "Auntie Anne's",
  "Jamba Juice",
  "Dutch Bros Coffee",
  "Peet's Coffee",
  "Tim Hortons",
  "Einstein Bros. Bagels",
  "Caribou Coffee",
  "Marriott",
  "Hilton",
  "Hyatt",
  "IHG",
  "Wyndham",
  "Choice Hotels",
  "Radisson",
  "Four Seasons",
  "Ritz-Carlton",
  "Omni",
  "Loews",
  "Drury",
  "Kimpton",
  "Aloft",
  "W Hotels",
  "JW Marriott",
  "Sheraton",
  "Westin",
  "Courtyard",
  "Residence Inn",
  "SpringHill Suites",
  "TownePlace Suites",
  "Homewood Suites",
  "Home2 Suites",
  "Hampton Inn",
  "DoubleTree",
  "Fairfield Inn",
  "Embassy Suites",
  "La Quinta",
  "Motel 6",
  "Red Roof Inn",
  "Extended Stay America",
  "Best Western",
  "Comfort Inn",
  "Days Inn",
  "Sleep Inn",
  "Microtel Inn & Suites",
  "Candlewood Suites",
  "Sonesta",
  "Four Points by Sheraton",
  "Ramada",
  "Red Lion",
  "Caesars Entertainment",
  "MGM Resorts",
  "Wynn Resorts",
  "Bellagio",
  "Mandalay Bay",
  "Harrah's",
  "Hertz",
  "Avis",
  "Budget",
  "Enterprise",
  "National",
  "Alamo",
  "Sixt",
  "Thrifty",
  "Dollar Rent A Car",
  "CarMax",
  "Carvana",
  "Vroom",
  "Discount Tire",
  "Les Schwab Tire Centers",
  "Tire Kingdom",
  "NTB",
  "Take 5 Oil Change",
  "Valvoline",
  "Meineke",
  "Midas",
  "Goodyear",
  "Firestone",
  "Pep Boys",
  "NAPA",
  "O'Reilly",
  "Advance Auto Parts",
  "AutoZone",
  "Jiffy Lube",
  "U-Haul",
  "Penske",
  "Ryder",
  "PODS",
  "Two Men and a Truck",
  "Mayflower",
  "Allied Van Lines",
  "Bekins",
  "Public Storage",
  "Extra Space Storage",
  "CubeSmart",
  "Life Storage",
  "StorageMart",
  "1-800-PACK-RAT",
  "Zippy Shell",
  "Mobile Mini",
];

// Grid clustering configuration
export const GRID_ROWS = 5;
export const GRID_COLS = 5;
